# This is a basic workflow to help you get started with Actions

name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    name: job1
    runs-on: [self-hosted, runner1]
    steps:
      - name: Turnstile
        uses: softprops/turnstyle@v0.1.5
        env:
          GITHUB_TOKEN: ${{secrets.WEBHOOK_WORKFLOW}}
      - name: Wait
        run: Start-Sleep -seconds 120
  
  job2:
    name: job2
    runs-on: [self-hosted, runner2]
    needs: [job1]
    steps:
      - name: Wait
        run: Start-Sleep -seconds 120
